### ISSUE TITLE
Delete a record

### ISSUE THREAD

**Issue by d2lam** [screwdriver-cd/models#105]
- [x] - Delete a pipeline: should delete all the jobs and builds belong to this pipeline
- [x] - Delete a job: should delete all the builds belong to this job
- [x] - Delete a build
- [x] - Delete a secret
- [ ] - Delete a user: should go through all the pipelines and revoke admin access 

This is all I can think of right now. Please feel free to add more requirements/acceptance criteria.

**Comment by d2lam** [comment]
@stjohnjohnson  So I was just thinking about whether we should allow deleting a build. Would that mess up our system (maybe not now but in the future)? And would a user ever want to delete a build? Deleting a job and deleting a pipeline make sense, but I'm not too sure about the deleting build use case.

**Comment by stjohnjohnson** [comment]
Don't need to delete user right now.  Everything else is done.
