### ISSUE TITLE
Pipelines model should not hardcode platform

### ISSUE THREAD

**Issue by tkyi** [screwdriver-cd/models#11]
Right now, all platforms are hardcoded to `generic@1`. 
(https://github.com/screwdriver-cd/models/blob/master/lib/pipeline.js#L29)

In the future, `platform` should be configurable

**Comment by stjohnjohnson** [comment]
The real question is, do we need platform?  Are we going to replace it with `template`

**Comment by tkyi** [comment]
I like `template`
