### ISSUE TITLE
Configure Models once for Datastore and Executor

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/models#18]
Right now we have to pass in datastore and executor each time we use a model.  Why not set them up once and pass the model collection into the plugins?

Would we ever have a model that has a different datastore than the others?  What about the executor?

If we go down that route, wouldn't a datastoreFactory or executorFactory be more appropriate?

**Comment by FenrirUnbound** [comment]
The initial idea was to use a Factory for constructing the models. It was decided against it due to "future proofing".

At this point, we can slowly switch the models over to be obtained from a Factory method, and introduce it PR by PR.

**Comment by FenrirUnbound** [comment]
To iterate our discussion from standup to here:

There were observed nuances with the current state of the models:

1. The models aren't treated like instances of an specific object. A `job` instance wouldn't represent a specific job and all its properties: it acts more as an interface to the datastore objects.
1. The model methods were treated as instance methods. It is now determined that some of those functions are better described as static methods, while some methods make sense to keep as instance methods.

**Comment by petey** [comment]
Factories handle this: PR #35, #43
